spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

application:
  security:
    jwt:
      expired-time: 3600
      secret: EWtQ,dsBAMWT5Qqy0X%8A]yPmmiyCHe_HG8Ub#]LA-+HWY^g,-LYC^YvYwQrG:57Eu,qk>cN)@Xun9>HowpDBx0#J1ds>KRnLyvD
